// generated/vue/components/combobox/ComboboxEmpty.vue
<script setup lang="ts">
  import "../../../../dist/components/input/input.css";
  import "../../../../dist/components/popover/popover.css";
  import "../../../../dist/components/combobox/combobox.css";
  import "../../../../dist/components/combobox/combobox.js";
  import { useAttrs } from "vue";
  import { cx, omitClass } from "../../runtime.ts";

  defineOptions({ inheritAttrs: false });

  interface Props {
  }

  defineProps<Props>();
  defineSlots<{ default?: () => any }>();
  const attrs = useAttrs();
</script>

<template>
  <combobox-empty
    v-bind="omitClass(attrs)"
    :class="cx(attrs.class)"
  >
    <slot />
  </combobox-empty>
</template>

// generated/svelte/components/combobox/ComboboxEmpty.svelte
<script module lang="ts">
  import "../../../../dist/components/input/input.css";
  import "../../../../dist/components/popover/popover.css";
  import "../../../../dist/components/combobox/combobox.css";
  import "../../../../dist/components/combobox/combobox.js";
</script>

<script lang="ts">
  import type { Snippet } from "svelte";
  import { cx, type DashbaseCustomElementProps } from "../../runtime.ts";

  interface Props extends DashbaseCustomElementProps {
    children?: Snippet;
  }

  let { class: className = "", children, ...rest }: Props = $props();
</script>

<combobox-empty
  {...rest}
  class={cx(className)}
>
  {@render children?.()}
</combobox-empty>
