// generated/svelte/components/combobox/ComboboxPanelManual.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { cx, type DashbaseCustomElementProps } from "../../runtime.ts";

  interface Props extends DashbaseCustomElementProps {
    children?: Snippet;
  }

  let { class: className = "", children, ...rest }: Props = $props();
</script>

<popover-panel
  popover
  role="listbox"
  {...rest}
  class={cx(className)}
>
  {@render children?.()}
</popover-panel>

// generated/vue/components/combobox/ComboboxPanelManual.vue
<script setup lang="ts">
  import { useAttrs } from "vue";
  import { cx, omitClass } from "../../runtime.ts";

  defineOptions({ inheritAttrs: false });

  interface Props {
  }

  defineProps<Props>();
  defineSlots<{ default?: () => any }>();
  const attrs = useAttrs();
</script>

<template>
  <popover-panel
    v-bind="omitClass(attrs)"
    popover
    role="listbox"
    :class="cx(attrs.class)"
  >
    <slot />
  </popover-panel>
</template>
