// generated/svelte/components/tabs/TabsTrigger.svelte
<script module lang="ts">
  import "../../../../dist/components/tabs/tabs.css";
  import "../../../../dist/components/tabs/tabs.js";
</script>

<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLButtonAttributes } from "svelte/elements";
  import { cx, type DashbaseCustomElementProps } from "../../runtime.ts";

  interface Props extends Omit<HTMLButtonAttributes, "children"> {
    children?: Snippet;
  }

  let { class: className = "", children, ...rest }: Props = $props();
</script>

<button
  role="tab"
  {...rest}
  class={cx(className)}
>
  {@render children?.()}
</button>

// generated/vue/components/tabs/TabsTrigger.vue
<script setup lang="ts">
  import "../../../../dist/components/tabs/tabs.css";
  import "../../../../dist/components/tabs/tabs.js";
  import { useAttrs } from "vue";
  import { cx, omitClass } from "../../runtime.ts";

  defineOptions({ inheritAttrs: false });

  interface Props {
  }

  defineProps<Props>();
  defineSlots<{ default?: () => any }>();
  const attrs = useAttrs();
</script>

<template>
  <button
    v-bind="omitClass(attrs)"
    role="tab"
    :class="cx(attrs.class)"
  >
    <slot />
  </button>
</template>
