// generated/vue/components/tabs/TabsContentManual.vue
<script setup lang="ts">
  import { useAttrs } from "vue";
  import { cx, omitClass } from "../../runtime.ts";

  defineOptions({ inheritAttrs: false });

  interface Props {
  }

  defineProps<Props>();
  defineSlots<{ default?: () => any }>();
  const attrs = useAttrs();
</script>

<template>
  <tab-panel
    v-bind="omitClass(attrs)"
    role="tabpanel"
    :class="cx(attrs.class)"
  >
    <slot />
  </tab-panel>
</template>

// generated/svelte/components/tabs/TabsContentManual.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { cx, type DashbaseCustomElementProps } from "../../runtime.ts";

  interface Props extends DashbaseCustomElementProps {
    children?: Snippet;
  }

  let { class: className = "", children, ...rest }: Props = $props();
</script>

<tab-panel
  role="tabpanel"
  {...rest}
  class={cx(className)}
>
  {@render children?.()}
</tab-panel>
