// generated/vue/components/tabs/TabsListManual.vue
<script setup lang="ts">
  import { useAttrs } from "vue";
  import { cx, omitClass } from "../../runtime.ts";

  defineOptions({ inheritAttrs: false });

  interface Props {
    orientation?: "horizontal" | "vertical";
  }

  const { orientation } = defineProps<Props>();
  defineSlots<{ default?: () => any }>();
  const attrs = useAttrs();
</script>

<template>
  <tab-list
    v-bind="omitClass(attrs)"
    role="tablist"
    :aria-orientation="orientation"
    :class="cx(attrs.class)"
  >
    <slot />
  </tab-list>
</template>

// generated/svelte/components/tabs/TabsListManual.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { cx, type DashbaseCustomElementProps } from "../../runtime.ts";

  interface Props extends DashbaseCustomElementProps {
    children?: Snippet;
    orientation?: "horizontal" | "vertical";
  }

  let { class: className = "", children, orientation, ...rest }: Props = $props();
</script>

<tab-list
  role="tablist"
  aria-orientation={orientation}
  {...rest}
  class={cx(className)}
>
  {@render children?.()}
</tab-list>
