// generated/svelte/components/popover/PopoverFooter.svelte
<script module lang="ts">
  import "../../../../dist/components/panel/panel.css";
  import "../../../../dist/components/popover/popover.css";
  import "../../../../dist/components/popover/popover.js";
</script>

<script lang="ts">
  import type { Snippet } from "svelte";
  import { cx, type DashbaseCustomElementProps } from "../../runtime.ts";

  interface Props extends DashbaseCustomElementProps {
    children?: Snippet;
  }

  let { class: className = "", children, ...rest }: Props = $props();
</script>

<panel-footer
  {...rest}
  class={cx(className)}
>
  {@render children?.()}
</panel-footer>

// generated/vue/components/popover/PopoverFooter.vue
<script setup lang="ts">
  import "../../../../dist/components/panel/panel.css";
  import "../../../../dist/components/popover/popover.css";
  import "../../../../dist/components/popover/popover.js";
  import { useAttrs } from "vue";
  import { cx, omitClass } from "../../runtime.ts";

  defineOptions({ inheritAttrs: false });

  interface Props {
  }

  defineProps<Props>();
  defineSlots<{ default?: () => any }>();
  const attrs = useAttrs();
</script>

<template>
  <panel-footer
    v-bind="omitClass(attrs)"
    :class="cx(attrs.class)"
  >
    <slot />
  </panel-footer>
</template>
