// generated/vue/components/popover/PopoverPanelManual.vue
<script setup lang="ts">
  import { useAttrs } from "vue";
  import { cx, omitClass } from "../../runtime.ts";

  defineOptions({ inheritAttrs: false });

  interface Props {
    wide?: boolean;
    alignEnd?: boolean;
    above?: boolean;
    submenu?: boolean;
    contextMenu?: boolean;
  }

  const { wide = false, alignEnd = false, above = false, submenu = false, contextMenu = false } = defineProps<Props>();
  defineSlots<{ default?: () => any }>();
  const attrs = useAttrs();
</script>

<template>
  <popover-panel
    v-bind="omitClass(attrs)"
    popover
    :role="role"
    :class="cx(attrs.class, wide && "wide", alignEnd && "align-end", above && "above", submenu && "submenu", contextMenu && "context-menu")"
  >
    <slot />
  </popover-panel>
</template>

// generated/svelte/components/popover/PopoverPanelManual.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { cx, type DashbaseCustomElementProps } from "../../runtime.ts";

  interface Props extends DashbaseCustomElementProps {
    children?: Snippet;
    wide?: boolean;
    alignEnd?: boolean;
    above?: boolean;
    submenu?: boolean;
    contextMenu?: boolean;
  }

  let { class: className = "", children, wide = false, alignEnd = false, above = false, submenu = false, contextMenu = false, ...rest }: Props = $props();
</script>

<popover-panel
  popover
  role={role}
  {...rest}
  class={cx(className, wide && "wide", alignEnd && "align-end", above && "above", submenu && "submenu", contextMenu && "context-menu")}
>
  {@render children?.()}
</popover-panel>
