// generated/svelte/components/carousel/Carousel.svelte
<script module lang="ts">
  import "../../../../dist/components/carousel/carousel.css";
  import "../../../../dist/components/carousel/carousel.js";
</script>

<script lang="ts">
  import type { Snippet } from "svelte";
  import { cx, type DashbaseCustomElementProps } from "../../runtime.ts";

  interface Props extends DashbaseCustomElementProps {
    children?: Snippet;
    vertical?: boolean;
  }

  let { class: className = "", children, vertical = false, ...rest }: Props = $props();
</script>

<ui-carousel
  {...rest}
  class={cx(className, vertical && "vertical")}
>
  {@render children?.()}
</ui-carousel>

// generated/vue/components/carousel/Carousel.vue
<script setup lang="ts">
  import "../../../../dist/components/carousel/carousel.css";
  import "../../../../dist/components/carousel/carousel.js";
  import { useAttrs } from "vue";
  import { cx, omitClass } from "../../runtime.ts";

  defineOptions({ inheritAttrs: false });

  interface Props {
    vertical?: boolean;
  }

  const { vertical = false } = defineProps<Props>();
  defineSlots<{ default?: () => any }>();
  const attrs = useAttrs();
</script>

<template>
  <ui-carousel
    v-bind="omitClass(attrs)"
    :class="cx(attrs.class, vertical && "vertical")"
  >
    <slot />
  </ui-carousel>
</template>
