// generated/svelte/components/carousel/CarouselDots.svelte
<script module lang="ts">
  import "../../../../dist/components/carousel/carousel.css";
  import "../../../../dist/components/carousel/carousel.js";
</script>

<script lang="ts">
  import type { Snippet } from "svelte";
  import { cx, type DashbaseCustomElementProps } from "../../runtime.ts";

  interface Props extends DashbaseCustomElementProps {
    children?: Snippet;
  }

  let { class: className = "", children, ...rest }: Props = $props();
</script>

<carousel-dots
  {...rest}
  class={cx(className)}
>
  {@render children?.()}
</carousel-dots>

// generated/vue/components/carousel/CarouselDots.vue
<script setup lang="ts">
  import "../../../../dist/components/carousel/carousel.css";
  import "../../../../dist/components/carousel/carousel.js";
  import { useAttrs } from "vue";
  import { cx, omitClass } from "../../runtime.ts";

  defineOptions({ inheritAttrs: false });

  interface Props {
  }

  defineProps<Props>();
  defineSlots<{ default?: () => any }>();
  const attrs = useAttrs();
</script>

<template>
  <carousel-dots
    v-bind="omitClass(attrs)"
    :class="cx(attrs.class)"
  >
    <slot />
  </carousel-dots>
</template>
