// generated/vue/components/carousel/CarouselPrevButtonManual.vue
<script setup lang="ts">
  import { useAttrs } from "vue";
  import { cx, omitClass } from "../../runtime.ts";

  defineOptions({ inheritAttrs: false });

  interface Props {
  }

  defineProps<Props>();
  defineSlots<{ default?: () => any }>();
  const attrs = useAttrs();
</script>

<template>
  <button
    v-bind="omitClass(attrs)"
    data-carousel-prev
    :class="cx(attrs.class)"
  >
    <slot />
  </button>
</template>

// generated/svelte/components/carousel/CarouselPrevButtonManual.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLButtonAttributes } from "svelte/elements";
  import { cx, type DashbaseCustomElementProps } from "../../runtime.ts";

  interface Props extends Omit<HTMLButtonAttributes, "children"> {
    children?: Snippet;
  }

  let { class: className = "", children, ...rest }: Props = $props();
</script>

<button
  data-carousel-prev
  {...rest}
  class={cx(className)}
>
  {@render children?.()}
</button>
