// generated/vue/components/carousel/CarouselGroup.vue
<script setup lang="ts">
  import "../../../../dist/components/carousel/carousel.css";
  import "../../../../dist/components/carousel/carousel.js";
  import { useAttrs } from "vue";
  import { cx, omitClass } from "../../runtime.ts";

  defineOptions({ inheritAttrs: false });

  interface Props {
  }

  defineProps<Props>();
  defineSlots<{ default?: () => any }>();
  const attrs = useAttrs();
</script>

<template>
  <item-group
    v-bind="omitClass(attrs)"
    :class="cx(attrs.class)"
  >
    <slot />
  </item-group>
</template>

// generated/svelte/components/carousel/CarouselGroup.svelte
<script module lang="ts">
  import "../../../../dist/components/carousel/carousel.css";
  import "../../../../dist/components/carousel/carousel.js";
</script>

<script lang="ts">
  import type { Snippet } from "svelte";
  import { cx, type DashbaseCustomElementProps } from "../../runtime.ts";

  interface Props extends DashbaseCustomElementProps {
    children?: Snippet;
  }

  let { class: className = "", children, ...rest }: Props = $props();
</script>

<item-group
  {...rest}
  class={cx(className)}
>
  {@render children?.()}
</item-group>
